// <auto-generated />
using System;
using Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(CuahangDbContext))]
    [Migration("20221021034008_one")]
    partial class one
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.ModelsClass.Giohang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("IDKhach")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKhach");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("Trangthai");

                    b.HasKey("ID");

                    b.ToTable("Giohang", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Giohangchitiet", b =>
                {
                    b.Property<Guid>("IDGiohang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanpham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal")
                        .HasColumnName("Giatien");

                    b.Property<decimal>("Soluong")
                        .HasColumnType("Decimal")
                        .HasColumnName("Soluong");

                    b.HasKey("IDGiohang", "IDSanpham");

                    b.HasIndex("IDSanpham");

                    b.ToTable("GiohangChitiet", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Sanpham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal")
                        .HasColumnName("Giatien");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("Soluong");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("Trangthai");

                    b.HasKey("Id");

                    b.ToTable("Sanpham", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Giohangchitiet", b =>
                {
                    b.HasOne("Data.ModelsClass.Giohang", "Giohang")
                        .WithMany("Giohangchitiets")
                        .HasForeignKey("IDGiohang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Giohang");

                    b.HasOne("Data.ModelsClass.Sanpham", "Sanpham")
                        .WithMany("Giohangchitiets")
                        .HasForeignKey("IDSanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sanpham");

                    b.Navigation("Giohang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("Data.ModelsClass.Giohang", b =>
                {
                    b.Navigation("Giohangchitiets");
                });

            modelBuilder.Entity("Data.ModelsClass.Sanpham", b =>
                {
                    b.Navigation("Giohangchitiets");
                });
#pragma warning restore 612, 618
        }
    }
}
